# Deze file regelt de definitie en beheer van de applicatie. 
# De verschillende functies en componenten:
# - definiëren en vullen van de volumes
# - configureren van de services

# Swagger geeft de mogelijkheid een browsergebaseerde editor te gebruiken
#   waar je je API-specificaties kunt schrijven en bewerken in de OpenAPI Specification (OAS) formaat.
#   Het biedt real-time feedback en validatie van je specificaties.

volumes:
    db_data:

services:
    postgrest:
        image: postgrest/postgrest:v12.0.3
        ports:
            - "3000:3000"
        environment:
            # PGRST_DB_URI=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database-postgres:5432/${DATABASE_NAME}
            PGRST_DB_URI: postgres://authenticator:postgres@db:5432/postgres
            PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
            PGRST_DB_SCHEMA: api
            PGRST_DB_ANON_ROLE: web_anon
        depends_on:
            - db

    db:
        image: postgres:16.3
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./db/sql:/docker-entrypoint-initdb.d

    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            API_URL: http://localhost:3000/